spring:
  application:
    name: letsplay-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/letsplay}
    username: ${SPRING_DATASOURCE_USERNAME:letsplay}
    password: ${SPRING_DATASOURCE_PASSWORD:letsplay}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password

server:
  port: 8082

temporal:
  target: ${TEMPORAL_TARGET:127.0.0.1:7233}
